version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:5000'
    volumes:
      - ./api:/api
      - ./scripts:/scripts 
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: /scripts/wait-for-it.sh db:5432 --timeout=30 -- python run.py  


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '${CLIENT_PORT}:3000'
    volumes:
      - ./client:/client
    depends_on:
      - api



  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
